[project]
name = "apis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "pydantic>=2.11.7",
    "regex>=2025.7.34",
    "sqlalchemy>=2.0.42",
    "uvicorn>=0.35.0",
]
